title: Java
baseurl: /java-guide
url: ""
author: Silas Krause
github_username:  krsilas
collections:
  chapters:
    output: true
sass:
    sass_dir: _sass
    style: compressed
exclude: [assets/resources]
